apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- ../../base/developers-nightmare

images:
- name: ghcr.io/thomasvitale/developers-nightmare
  newTag: f06d2ccf80be51c88ca142d28fa774976620983f
