apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- ../../base/developers-nightmare

images:
- name: ghcr.io/thomasvitale/developers-nightmare
  newTag: f008db0c0ed4a4fe525f34eddb39b815eae8569b
