apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- ../../base/developers-nightmare

images:
- name: ghcr.io/thomasvitale/developers-nightmare
  newTag: d958103cffbcfa8fdc14ee3b5894288307e9bad1
