apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- ../../base/developers-nightmare

images:
- name: ghcr.io/thomasvitale/developers-nightmare
  newTag: d9cba89c891254aad828a6676fba64322032b5aa
