apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- ../../base/developers-nightmare

images:
- name: ghcr.io/thomasvitale/developers-nightmare
  newTag: b98f1b8f59eba2c153f47d9c78b712bd355a8a31
