---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-developers-nightmare
  namespace: apps
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.2
  instances: 1
  storage:
    size: 1Gi
