---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: developers-nightmare
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: supply-chain
      containers:
        - name: workload
          image: ghcr.io/thomasvitale/developers-nightmare:c8a9256bed657f6245ef9f4803b6f9144a7dc749
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-developers-nightmare-app
                  key: jdbc-uri
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-developers-nightmare-app
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-developers-nightmare-app
                  key: password
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
