name: Production Stage

on:
  repository_dispatch:
    types: [app-delivery]

permissions:
  contents: read

jobs:
  update:
    name: Update application version
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      APP_TARGET: ${{ github.event.client_payload.app_target }}
      APP_IMAGE: ${{ github.event.client_payload.app_image }}
      APP_NAME: ${{ github.event.client_payload.app_name }}
      APP_VERSION: ${{ github.event.client_payload.app_version }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
      - name: Update image version
        run: |
          cd apps/${{ env.APP_TARGET }}/${{ env.APP_NAME }}
          kustomize edit set image ${{ env.APP_IMAGE }}:${{ env.APP_VERSION }}
          sed -i 's/ref=[\w+]/${{ env.APP_VERSION }}/' kustomization.yml
      - name: Commit updated manifests
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: "Update ${{ env.APP_NAME }} to version ${{ env.APP_VERSION }}"
          branch: main
